2025-06-13 12:30:30,078 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e1c931005e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /config/v1/agents
2025-06-13 12:30:30,079 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e1c931019c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /config/v1/agents
2025-06-13 12:30:30,079 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7e1c93100fa0>: Failed to establish a new connection: [Errno 111] Connection refused')': /config/v1/agents
2025-06-13 14:06:20,446 - elastic_transport.transport - INFO - HEAD https://vs-production.es.ap-south-1.aws.elastic-cloud.com:9243/ [status:401 duration:0.348s]
2025-06-13 14:06:20,446 - document_validation - ERROR - Elasticsearch connection failed
2025-06-13 14:06:20,685 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d209069a3b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /config/v1/agents
2025-06-13 14:06:20,686 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d209069a530>: Failed to establish a new connection: [Errno 111] Connection refused')': /config/v1/agents
2025-06-13 14:06:20,687 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d209069a6b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /config/v1/agents
2025-06-13 14:06:20,768 - elastic_transport.transport - INFO - HEAD https://vs-production.es.ap-south-1.aws.elastic-cloud.com:9243/ [status:401 duration:0.291s]
2025-06-13 14:06:20,768 - document_validation - ERROR - Elasticsearch connection failed
2025-06-13 15:43:27,740 - elastic_transport.transport - INFO - HEAD https://vs-production.es.ap-south-1.aws.elastic-cloud.com:9243/ [status:403 duration:0.275s]
2025-06-13 15:43:27,741 - document_validation - ERROR - Elasticsearch connection failed
2025-06-13 15:43:27,922 - elastic_transport.transport - INFO - HEAD https://vs-production.es.ap-south-1.aws.elastic-cloud.com:9243/ [status:403 duration:0.151s]
2025-06-13 15:43:27,922 - document_validation - ERROR - Elasticsearch connection failed
2025-06-13 15:43:27,977 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c3d9b7cb490>: Failed to establish a new connection: [Errno 111] Connection refused')': /config/v1/agents
2025-06-13 15:43:27,977 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c3d9b7cb640>: Failed to establish a new connection: [Errno 111] Connection refused')': /config/v1/agents
2025-06-13 15:43:27,977 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c3d9b7cb7c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /config/v1/agents
